# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "410ed0f0d2bcff00e0bf401dc1d649d3"
name = "wait"
application_url = "https://atlas-parking-later-placed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wait-for-all.myshopify.com"

[auth]
redirect_urls = [
  "https://atlas-parking-later-placed.trycloudflare.com/auth/callback",
  "https://atlas-parking-later-placed.trycloudflare.com/auth/shopify/callback",
  "https://atlas-parking-later-placed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2022-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://ebcf-2402-800-61b3-5275-c8b2-f673-787d-27fd.ngrok.io/api/gdpr/customer-redact"
  customer_data_request_url = "https://ebcf-2402-800-61b3-5275-c8b2-f673-787d-27fd.ngrok.io/api/gdpr/customer-data"
  shop_deletion_url = "https://ebcf-2402-800-61b3-5275-c8b2-f673-787d-27fd.ngrok.io/api/gdpr/shop-redact"

[app_proxy]
url = "https://atlas-parking-later-placed.trycloudflare.com/storefront"
subpath = "wholesales"
prefix = "apps"

[pos]
embedded = false
