# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3e0038ca6adc5fbc03ea513c624ce35c"
name = "luxury-shipping-app"
application_url = "https://planning-matthew-dm-transport.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "wait-for-all.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_customers,read_customers,read_product_listings,read_products,read_themes,unauthenticated_read_product_listings,write_products,write_themes"

[auth]
redirect_urls = [
  "https://planning-matthew-dm-transport.trycloudflare.com/auth/callback",
  "https://planning-matthew-dm-transport.trycloudflare.com/auth/shopify/callback",
  "https://planning-matthew-dm-transport.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[app_proxy]
url = "https://planning-matthew-dm-transport.trycloudflare.com/storefront"
subpath = "wholesales"
prefix = "apps"

[pos]
embedded = false
